function showTab(name,el){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.getElementById('panel-'+name).classList.add('active');el.classList.add('active');setTimeout(function(){var m={tts:loadEngines,games:loadGames,music:loadTracks,live:loadLive,alarm:loadAlarmTimer,timer:loadAlarmTimer,screenshot:loadScreenshotSettings,random:loadRandomPhrases,mic:loadMicSettings,llm:loadLlmStatus,character:loadCharacterPresets,mcp:loadMcpConfig,system:loadSystemInfo};if(m[name])m[name]()},50)}
async function api(path, body){const method=body?'POST':'GET';const o={method,headers:{'Accept':'application/json','Content-Type':'application/json'}};if(body)o.body=JSON.stringify(body);const r=await fetch('/api/'+path,o);return r.json()}
function setStatus(msg,type){const el=document.getElementById('status');el.textContent=msg;el.className='status '+type}

let _defaultVoice = '';

async function loadOutputDevices(){try{const r=await api('output_devices');const sel=document.getElementById('outputDevice');if(!sel)return;sel.innerHTML='<option value="">(по умолчанию)</option>';for(const d of r.devices||[]){const opt=document.createElement('option');opt.value=d.id;opt.textContent=d.name;if(d.id===r.current)opt.selected=true;sel.appendChild(opt)}}catch(e){console.error('loadOutputDevices',e)}}
async function loadEngines(){try{const re=await api('tts_engines');const selE=document.getElementById('ttsEngine');if(!selE)return;selE.innerHTML='';let cur=re.current_engine||'piper';for(const e of re.engines){const opt=document.createElement('option');opt.value=e;opt.textContent=e==='xtts'?'XTTS v2':'Piper';if(e===cur)opt.selected=true;selE.appendChild(opt)}const rs=await api('settings');_defaultVoice=rs.default_voice||'';const g=x=>document.getElementById(x);const el=g('volLabel');if(el)el.textContent=Math.round(rs.volume*100)+'%';if(g('volume'))g('volume').value=Math.round(rs.volume*100);if(g('enabled'))g('enabled').checked=rs.enabled;if(g('enabledLabel'))g('enabledLabel').textContent=rs.enabled?'Включено':'Выключено';if(g('gameInviteText'))g('gameInviteText').value=rs.game_invite_text||'';const spd=rs.speed||1.0;if(g('speedLabel'))g('speedLabel').textContent=spd.toFixed(1)+'x';if(g('speed'))g('speed').value=Math.round(spd*100);await loadOutputDevices();await loadVoicesForEngine(cur)}catch(e){console.error('loadEngines',e)}}
async function onEngineChange(){try{const e=document.getElementById('ttsEngine');if(!e)return;_defaultVoice='';await loadVoicesForEngine(e.value)}catch(e){console.error('onEngineChange',e)}}
async function loadVoicesForEngine(engine){try{const r=await api('voices');const sel=document.getElementById('voice');if(!sel)return;const chatSel=document.getElementById('llmChatVoice');sel.innerHTML='';const curEngineEl=document.getElementById('ttsEngine');const curEngine=curEngineEl?curEngineEl.value:'piper';let found=false;for(const v of r.voices){if(curEngine==='piper'&&v.startsWith('xtts:'))continue;if(curEngine==='xtts'&&!v.startsWith('xtts:'))continue;const opt=document.createElement('option');opt.value=v;opt.textContent=v.replace('xtts:','');if(v===_defaultVoice){opt.selected=true;found=true}sel.appendChild(opt);if(chatSel){const opt2=document.createElement('option');opt2.value=v;opt2.textContent=v.replace('xtts:','');chatSel.appendChild(opt2)}}if(!found&&_defaultVoice){const opt=document.createElement('option');opt.value=_defaultVoice;opt.textContent=_defaultVoice.replace('xtts:','')+' (текущий)';opt.selected=true;sel.appendChild(opt)}}catch(e){console.error('loadVoicesForEngine',e)}}

async function loadGames(){const r=await api('games');const gl=document.getElementById('gameList');gl.innerHTML='';for(const g of r.games){const div=document.createElement('div');div.className='game-row';const ic=document.createElement('span');ic.className='gicon';ic.textContent=g.icon;const inp=document.createElement('input');inp.value=g.start_text;inp.dataset.gid=g.id;div.appendChild(ic);div.appendChild(inp);gl.appendChild(div)}}

async function saveGameSettings(){const invites=[];document.querySelectorAll('#gameList .game-row input').forEach(i=>invites.push({id:i.dataset.gid,text:i.value}));const common=document.getElementById('gameInviteText').value.trim();await api('save_game_settings',{games:invites,invite_text:common});setStatus('Игры сохранены','ok')}

async function loadTracks(){const r=await api('tracks');const el=document.getElementById('trackList');el.innerHTML='';for(const t of r.tracks){const d=document.createElement('div');d.style.cssText='cursor:pointer;padding:4px;border-radius:6px;margin:2px 0';d.onmouseenter=()=>d.style.background='#2a2a4e';d.onmouseleave=()=>d.style.background='';d.onclick=()=>musicPlay(t);d.className='mtrack';d.textContent=t;el.appendChild(d)}if(r.loop)document.getElementById('loopBtn').textContent='✅ Loop';if(r.autoplay)document.getElementById('autoBtn').textContent='✅ Autoplay';const volPct=Math.round((r.volume||0.5)*100);document.getElementById('musicVolLabel').textContent=volPct+'%';document.getElementById('musicVol').value=volPct}
async function musicPlay(track){if(!track)track=document.querySelector('#trackList .mtrack')?.textContent;if(!track)return;await api('music_play',{track});setStatus('Играет: '+track,'ok');loadTracks()}
async function musicStop(){await api('music_stop');setStatus('Стоп','ok');loadTracks()}
async function musicNext(){const r=await api('music_next');setStatus(r.result||'Next','ok');loadTracks()}
async function musicPrev(){const r=await api('music_prev');setStatus(r.result||'Prev','ok');loadTracks()}
async function musicRandom(){const r=await api('music_random');setStatus(r.result||'Random','ok');loadTracks()}
async function toggleLoop(){const el=document.getElementById('loopBtn');if(el.textContent.includes('✅')){await api('music_loop',{loop:false});el.textContent='🔁 Loop'}else{await api('music_loop',{loop:true});el.textContent='✅ Loop'}}
async function toggleAutoplay(){const el=document.getElementById('autoBtn');if(el.textContent.includes('✅')){await api('music_autoplay',{autoplay:false});el.textContent='▶▶ Autoplay'}else{await api('music_autoplay',{autoplay:true});el.textContent='✅ Autoplay'}}
async function setMusicVolume(v){document.getElementById('musicVolLabel').textContent=v+'%';await api('music_volume',{volume:parseInt(v)/100})}
async function saveMusicVol(){const v=parseInt(document.getElementById('musicVol').value)/100;await api('save_music_vol',{volume:v});setStatus('Громкость сохранена','ok')}
async function loadLive(){const r=await api('live_settings');document.getElementById('liveInterval').value=r.interval||30;const phrases=r.phrases&&r.phrases.length?r.phrases:['Привет!','Как дела?','Давай играть!','Скучаю по тебе!'];document.getElementById('livePhrases').value=phrases.join('\n')}
async function saveLive(){const interval=parseInt(document.getElementById('liveInterval').value)||30;const ta=document.getElementById('livePhrases');const phrases=ta.value.split('\n').map(s=>s.trim()).filter(s=>s);await api('save_live',{interval,phrases});document.getElementById('liveStatus').textContent='✅ Сохранено';setTimeout(()=>document.getElementById('liveStatus').textContent='● Готов',2000);setStatus('','ok')}

async function loadAlarmTimer(){const r=await api('alarm_timer_settings');const a=r.alarm,t=r.timer;document.getElementById('alarmEnabled').checked=a.enabled;document.getElementById('alarmEnabledLabel').textContent=a.enabled?'Включено':'Выключено';document.getElementById('alarmTime').value=a.time;document.getElementById('alarmText').value=a.text;document.getElementById('alarmRepeat').value=a.repeat;document.getElementById('alarmReplay').value=a.replay_interval||0;document.getElementById('alarmStopAfter').value=a.stop_after||0;document.getElementById('alarmAutoRepeat').checked=a.auto_repeat;document.getElementById('alarmAutoLabel').textContent=a.auto_repeat?'Автоповтор: да':'Автоповтор: нет';document.getElementById('timerEnabled').checked=t.enabled;document.getElementById('timerEnabledLabel').textContent=t.enabled?'Включено':'Выключено';document.getElementById('timerDuration').value=t.duration;document.getElementById('timerText').value=t.text;document.getElementById('timerRepeat').value=t.repeat;document.getElementById('timerReplay').value=t.replay_interval||0;document.getElementById('timerStopAfter').value=t.stop_after||0;document.getElementById('timerAutoRepeat').checked=t.auto_repeat;document.getElementById('timerAutoLabel').textContent=t.auto_repeat?'Автоповтор: да':'Автоповтор: нет';loadAlarmSongs(a.song||'',t.song||'')}

async function loadAlarmSongs(selAlarm,selTimer){const r=await api('tracks');const selA=document.getElementById('alarmSong'),selT=document.getElementById('timerSong');selA.innerHTML='<option value="">(без песни)</option>';selT.innerHTML='<option value="">(без песни)</option>';for(const t of r.tracks){const o1=document.createElement('option');o1.value=t;o1.textContent=t;if(t===selAlarm)o1.selected=true;selA.appendChild(o1);const o2=document.createElement('option');o2.value=t;o2.textContent=t;if(t===selTimer)o2.selected=true;selT.appendChild(o2)}}
async function saveAlarmTimer(){const a={enabled:document.getElementById('alarmEnabled').checked,time:document.getElementById('alarmTime').value,text:document.getElementById('alarmText').value.trim(),song:document.getElementById('alarmSong').value,repeat:parseInt(document.getElementById('alarmRepeat').value)||1,auto_repeat:document.getElementById('alarmAutoRepeat').checked,replay_interval:parseInt(document.getElementById('alarmReplay').value)||0,stop_after:parseInt(document.getElementById('alarmStopAfter').value)||0};const t={enabled:document.getElementById('timerEnabled').checked,duration:parseInt(document.getElementById('timerDuration').value)||300,text:document.getElementById('timerText').value.trim(),song:document.getElementById('timerSong').value,repeat:parseInt(document.getElementById('timerRepeat').value)||1,auto_repeat:document.getElementById('timerAutoRepeat').checked,replay_interval:parseInt(document.getElementById('timerReplay').value)||0,stop_after:parseInt(document.getElementById('timerStopAfter').value)||0};await api('save_alarm_timer',{alarm:a,timer:t});document.getElementById('alarmStatus').textContent='✅ Сохранено';setTimeout(()=>{document.getElementById('alarmStatus').textContent='● Готов'},2000)}

async function saveDefault(){const voice=document.getElementById('voice').value;const vol=parseInt(document.getElementById('volume').value);const en=document.getElementById('enabled').checked;const speed=parseInt(document.getElementById('speed').value)/100;const engine=document.getElementById('ttsEngine').value;const outDev=document.getElementById('outputDevice').value;setStatus('Сохранение...','ok');await api('save_settings',{default_voice:voice,volume:vol/100,enabled:en,speed:speed,tts_engine:engine,output_device:outDev?parseInt(outDev):null});setStatus('Сохранено','ok')}
async function speak(){const text=document.getElementById('text').value.trim();if(!text)return;const voiceEl=document.getElementById('voice');const voice=voiceEl?voiceEl.value:'';setStatus('Говорю...','ok');document.getElementById('speakBtn').disabled=true;const r=await api('speak',{text,voice});document.getElementById('speakBtn').disabled=false;if(r.error)setStatus('Ошибка: '+r.error,'err');else setStatus(r.result||'Готово','ok')}
async function stopSpeak(){await api('stop');setStatus('Остановлено','ok')}
async function toggleEnabled(){const e=document.getElementById('enabled').checked;await api('settings',{enabled:e});document.getElementById('enabledLabel').textContent=e?'Включено':'Выключено';document.getElementById('speakBtn').disabled=!e;setStatus(e?'Включено':'Выключено',e?'ok':'err')}
async function setVolume(v){document.getElementById('volLabel').textContent=v+'%';await api('settings',{volume:v/100})}
async function setSpeed(v){document.getElementById('speedLabel').textContent=(v/100).toFixed(1)+'x';await api('settings',{speed:v/100})}
async function loadScreenshotSettings(){const r=await api('screenshot_settings');document.getElementById('screenshotEnabled').checked=r.enabled;document.getElementById('screenshotEnabledLabel').textContent=r.enabled?'Включено':'Выключено';document.getElementById('screenshotDelay').value=r.delay}
async function saveScreenshotSettings(){const en=document.getElementById('screenshotEnabled').checked;const delay=parseInt(document.getElementById('screenshotDelay').value)||500;await api('save_screenshot_settings',{enabled:en,delay:delay});document.getElementById('screenshotEnabledLabel').textContent=en?'Включено':'Выключено';document.getElementById('screenshotStatus').textContent='✅ Сохранено';setTimeout(()=>{document.getElementById('screenshotStatus').textContent='● Готов'},2000)}
async function testScreenshot(){const delay=parseInt(document.getElementById('screenshotDelay').value)||500;document.getElementById('screenshotStatus').textContent='📸 Снимок...';const r=await api('screenshot_test',{delay:delay});if(r.image){const img=document.getElementById('screenshotImg');img.src='data:image/png;base64,'+r.image;document.getElementById('screenshotPreview').style.display='block';document.getElementById('screenshotStatus').textContent='✅ Готово ('+delay+'мс)'}else{document.getElementById('screenshotStatus').textContent='❌ Ошибка: '+(r.error||'нет данных')}}
async function clearScreenshot(){document.getElementById('screenshotPreview').style.display='none';document.getElementById('screenshotImg').src='';await api('screenshot_clear');document.getElementById('screenshotStatus').textContent='🧹 Очищено'}

async function loadRandomPhrases(){const r=await api('random_phrases');document.getElementById('randomPhrases').value=(r.phrases||[]).join('\n');document.getElementById('randomInterval').value=r.interval||10;document.getElementById('randomStatus').textContent='● Готов'}
async function saveRandomPhrases(){const text=document.getElementById('randomPhrases').value;const phrases=text.split('\n').map(s=>s.trim()).filter(s=>s.length>0);const interval=parseInt(document.getElementById('randomInterval').value)||10;await api('save_random_phrases',{phrases:phrases,interval:interval});document.getElementById('randomStatus').textContent='✅ Сохранено';setTimeout(()=>{document.getElementById('randomStatus').textContent='● Готов'},2000)}

async function loadMicSettings(){try{const r=await api('mic_settings');if(!r||r.error){document.getElementById('micStatus').textContent='⚠ Mic недоступен';return}const selDev=document.getElementById('micDevice');selDev.innerHTML='<option value="">(по умолчанию)</option>';for(const d of r.devices||[]){const opt=document.createElement('option');opt.value=d.id;opt.textContent=d.name;if(d.id===r.device_id)opt.selected=true;selDev.appendChild(opt)}document.getElementById('micLang').value=r.lang||'ru';document.getElementById('micModel').value=r.model||'tiny';const vad=r.vad_threshold!==undefined?r.vad_threshold:0.05;const vadVal=Math.round(vad*100);document.getElementById('micSensitivity').value=vadVal;document.getElementById('micSensitivityLabel').textContent=vad.toFixed(3);if(r.listening){document.getElementById('micEnabled').checked=true;document.getElementById('micEnabledLabel').textContent='Включено';document.getElementById('micStartBtn').disabled=true;document.getElementById('micStopBtn').disabled=false}if(r.last_transcript)document.getElementById('micTranscript').value=r.last_transcript}catch(e){document.getElementById('micStatus').textContent='⚠ Mic ошибка'}}
async function setMicSensitivity(v){const val=parseInt(v)/100;document.getElementById('micSensitivityLabel').textContent=val.toFixed(3);await api('mic_vad',{vad_threshold:val})}
async function toggleMic(){const en=document.getElementById('micEnabled').checked;document.getElementById('micEnabledLabel').textContent=en?'Включено':'Выключено';if(en){document.getElementById('micStartBtn').disabled=false}else{document.getElementById('micStartBtn').disabled=true;await stopMic()};document.getElementById('micStatus').textContent=en?'● Готов':'● Выключено'}
async function startMic(){const lang=document.getElementById('micLang').value;const model=document.getElementById('micModel').value;const device=document.getElementById('micDevice').value;document.getElementById('micStatus').textContent='🔄 Запуск...';const r=await api('mic_start',{lang:lang,model:model,device_id:device||null});if(r.error){document.getElementById('micStatus').textContent='❌ '+r.error;return}document.getElementById('micEnabled').checked=true;document.getElementById('micEnabledLabel').textContent='Включено';document.getElementById('micStartBtn').disabled=true;document.getElementById('micStopBtn').disabled=false;document.getElementById('micStatus').textContent='🎤 Слушаю...'}
async function stopMic(){document.getElementById('micStatus').textContent='🔄 Остановка...';await api('mic_stop');document.getElementById('micEnabled').checked=false;document.getElementById('micEnabledLabel').textContent='Выключено';document.getElementById('micStartBtn').disabled=false;document.getElementById('micStopBtn').disabled=true;document.getElementById('micStatus').textContent='● Остановлено'}
async function testMic(){document.getElementById('micStatus').textContent='🔄 Тест...';const r=await api('mic_test');if(r.error){document.getElementById('micStatus').textContent='❌ '+r.error;return}document.getElementById('micTranscript').value=r.text||'(тишина)';document.getElementById('micStatus').textContent='✅ Тест завершён'}
async function saveMicSettings(){try{await api('mic_settings',{lang:document.getElementById('micLang').value,model:document.getElementById('micModel').value,device_id:document.getElementById('micDevice').value||null,vad_threshold:parseInt(document.getElementById('micSensitivity').value)/100});document.getElementById('micStatus').textContent='✅ Сохранено';setTimeout(()=>document.getElementById('micStatus').textContent='● Готов',2000)}catch(e){document.getElementById('micStatus').textContent='❌ '+e.message}}

async function llmChat(){const t=document.getElementById('llmChatText');if(!t)return;const text=t.value.trim();if(!text)return;const el=document.getElementById('llmChatMessages');const v=document.getElementById('llmChatVoice');const voice=v?v.value:'';el.innerHTML=el.innerHTML.replace('<div style="color:#888;text-align:center;padding:20px">Начните диалог...</div>','')+'<div style="color:#4ade80;margin:4px 0"><b>Вы:</b> '+text.replace(/</g,'&lt;')+'</div>';t.value='';el.scrollTop=el.scrollHeight;try{const r=await api('llm_chat',{text,voice});if(r.error){el.innerHTML+='<div style="color:#f87171;margin:4px 0">❌ '+r.error.replace(/</g,'&lt;')+'</div>';return}el.innerHTML+='<div style="color:#eee;margin:4px 0"><b>'+(r.provider||'LLM')+':</b> '+((r.reply||'(пустой ответ)').replace(/</g,'&lt;').replace(/\n/g,'<br>'))+'</div>';el.scrollTop=el.scrollHeight}catch(e){el.innerHTML+='<div style="color:#f87171;margin:4px 0">❌ '+e.message.replace(/</g,'&lt;')+'</div>'}}
async function loadLlmStatus(){try{const r=await api('llm_connections');const g=document.getElementById('llmEnabled');if(g){g.checked=r.enabled;document.getElementById('llmEnabledLabel').textContent='LLM: '+(r.enabled?'Включено':'Выключено')}const providers={ollama:'Ollama',lmstudio:'Lmstudio',deepseek:'Deepseek',proxy:'Proxy'};for(const[p,name]of Object.entries(providers)){const el=document.getElementById('llm'+name+'Enabled');const lbl=document.getElementById('llm'+name+'Label');if(!el)continue;const prov=r[p]||{};el.checked=!!prov.enabled;if(lbl)lbl.textContent=(p==='ollama'?'🦙 Ollama':p==='lmstudio'?'💻 LM Studio':p==='deepseek'?'🔮 DeepSeek Free':'⚡ Ollama Proxy')+(prov.enabled?' ✅':'')}if(r.ollama){const o=document.getElementById('ollamaHost');if(o)o.value=r.ollama.host||'localhost';const op=document.getElementById('ollamaPort');if(op)op.value=r.ollama.port||11434;const oe=document.getElementById('llmOllamaFields');if(oe)oe.style.display=r.ollama.enabled?'block':'none'}if(r.lmstudio){const lh=document.getElementById('lmstudioHost');if(lh)lh.value=r.lmstudio.host||'localhost';const lp=document.getElementById('lmstudioPort');if(lp)lp.value=r.lmstudio.port||1234;const le=document.getElementById('llmLmstudioFields');if(le)le.style.display=r.lmstudio.enabled?'block':'none'}if(r.deepseek){const dk=document.getElementById('deepseekKey');if(dk)dk.value=r.deepseek.api_key||'';const dm=document.getElementById('deepseekModel');if(dm)dm.value=r.deepseek.model||'deepseek-chat';const de=document.getElementById('llmDeepseekFields');if(de)de.style.display=r.deepseek.enabled?'block':'none'}if(r.proxy){const ph=document.getElementById('proxyHost');if(ph)ph.value=r.proxy.host||'localhost';const pp=document.getElementById('proxyPort');if(pp)pp.value=r.proxy.port||4000;const pk=document.getElementById('proxyKey');if(pk)pk.value=r.proxy.api_key||'sk-ollama-proxy-key';const pe=document.getElementById('llmProxyFields');if(pe)pe.style.display=r.proxy.enabled?'block':'none';const pm=document.getElementById('proxyModel');if(pm&&r.proxy.model){pm.innerHTML='';const opt=document.createElement('option');opt.value=r.proxy.model;opt.textContent=r.proxy.model;opt.selected=true;pm.appendChild(opt)}}const ve=document.getElementById('llmVoiceEnabled');if(ve){ve.checked=r.voice_enabled!==false;document.getElementById('llmVoiceLabel').textContent='🗣 Озвучка ответов'+(r.voice_enabled!==false?' ✅':'')}const mm=document.getElementById('llmMcpMode');if(mm){mm.checked=!!r.mcp_mode;document.getElementById('llmMcpModeLabel').textContent='🎙 Режим микрофона (заполняет текст, отправка вручную)'+(r.mcp_mode?' ✅':'');if(r.mcp_mode){if(!_mcpPollTimer)_mcpPollTimer=setInterval(mcpPollTranscript,1500)}else{if(_mcpPollTimer){clearInterval(_mcpPollTimer);_mcpPollTimer=null}}}document.getElementById('llmStatus').textContent='● Готов'}catch(e){document.getElementById('llmStatus').textContent='❌ Ошибка: '+e.message;console.error('loadLlmStatus',e)}}
async function toggleLlmGlobal(enabled){try{await api('llm_connections',{enabled});document.getElementById('llmEnabledLabel').textContent='LLM: '+(enabled?'Включено':'Выключено');document.getElementById('llmStatus').textContent='✅ Сохранено';setTimeout(()=>document.getElementById('llmStatus').textContent='● Готов',2000)}catch(e){console.error('toggleLlmGlobal',e)}}
async function toggleLlm(provider,enabled){try{const data={provider,enabled};const provEl={ollama:'Ollama',lmstudio:'Lmstudio',deepseek:'Deepseek',proxy:'Proxy'}[provider];const hostEl=document.getElementById(provider+'Host');if(hostEl)data.host=hostEl.value;const portEl=document.getElementById(provider+'Port');if(portEl)data.port=parseInt(portEl.value)||11434;const modelEl=document.getElementById(provider+'Model');if(modelEl)data.model=modelEl.value;const keyEl=document.getElementById(provider+'Key');if(keyEl)data.api_key=keyEl.value;if(provider==='deepseek'){const dk=document.getElementById('deepseekKey');if(dk)data.api_key=dk.value}await api('llm_connections',data);await loadLlmStatus();document.getElementById('llmStatus').textContent='✅ Сохранено';setTimeout(()=>document.getElementById('llmStatus').textContent='● Готов',2000)}catch(e){console.error('toggleLlm',e)}}
async function toggleLlmVoice(enabled){try{await api('llm_connections',{voice_enabled:enabled});document.getElementById('llmVoiceLabel').textContent='🗣 Озвучка ответов'+(enabled?' ✅':'');document.getElementById('llmStatus').textContent='✅ Сохранено';setTimeout(()=>document.getElementById('llmStatus').textContent='● Готов',2000)}catch(e){console.error('toggleLlmVoice',e)}}
let _mcpPollTimer = null;
let _lastMcpText = '';

async function toggleLlmMcpMode(enabled){
  try{
    await api('llm_connections',{mcp_mode:enabled});
    document.getElementById('llmMcpModeLabel').textContent='🎙 Режим микрофона (заполняет текст, отправка вручную)'+(enabled?' ✅':'');
    document.getElementById('llmStatus').textContent='✅ Сохранено';
    setTimeout(()=>document.getElementById('llmStatus').textContent='● Готов',2000);
    if(enabled){
      if(!_mcpPollTimer)_mcpPollTimer=setInterval(mcpPollTranscript,1500);
      const micEn=document.getElementById('micEnabled');
      if(micEn&&!micEn.checked)await startMic();
    }else{
      if(_mcpPollTimer){clearInterval(_mcpPollTimer);_mcpPollTimer=null}
    }
  }catch(e){console.error('toggleLlmMcpMode',e)}
}

async function mcpPollTranscript(){
  try{
    const r=await api('mic_transcript');
    if(!r.listening)return;
    const txt=(r.text||'').trim();
    if(!txt||txt===_lastMcpText)return;
    _lastMcpText=txt;
    document.getElementById('llmChatText').value=txt;
  }catch(e){console.error('mcpPoll',e)}
}
async function saveLlmSettings(){try{const data={};const g=document.getElementById('llmEnabled');if(g)data.enabled=g.checked;for(const p of['ollama','lmstudio','deepseek','proxy']){const el=document.getElementById('llm'+p.charAt(0).toUpperCase()+p.slice(1)+'Enabled');if(!el)continue;if(el.checked){data.provider=p;const hostEl=document.getElementById(p+'Host');if(hostEl)data.host=hostEl.value;const portEl=document.getElementById(p+'Port');if(portEl)data.port=parseInt(portEl.value);const modelEl=document.getElementById(p+'Model');if(modelEl)data.model=modelEl.value;const keyEl=document.getElementById(p+'Key');if(keyEl)data.api_key=keyEl.value;if(p==='deepseek'){const dk=document.getElementById('deepseekKey');if(dk)data.api_key=dk.value}break}}const ve=document.getElementById('llmVoiceEnabled');if(ve)data.voice_enabled=ve.checked;const mm=document.getElementById('llmMcpMode');if(mm)data.mcp_mode=mm.checked;await api('llm_connections',data);await loadLlmStatus();document.getElementById('llmStatus').textContent='✅ Сохранено';setTimeout(()=>document.getElementById('llmStatus').textContent='● Готов',2000)}catch(e){console.error('saveLlmSettings',e)}}
function llmChatClear(){const el=document.getElementById('llmChatMessages');if(el)el.innerHTML='<div style="color:#888;text-align:center;padding:20px">Начните диалог...</div>'}
async function testLlmConnections(){try{let active='ollama';for(const p of['ollama','lmstudio','deepseek','proxy']){const el=document.getElementById('llm'+p.charAt(0).toUpperCase()+p.slice(1)+'Enabled');if(el&&el.checked){active=p;break}}document.getElementById('llmStatus').textContent='🔄 Тестируем '+active+'...';const r=await api('llm_test',{provider:active});const sel=document.getElementById(active+'Model');if(sel){sel.innerHTML='';if(r.models&&r.models.length){for(const m of r.models){const opt=document.createElement('option');opt.value=m;opt.textContent=m;sel.appendChild(opt)}}else{const opt=document.createElement('option');opt.value='';opt.textContent='— нет моделей —';sel.appendChild(opt)}}document.getElementById('llmStatus').textContent='✅ Тест завершён: '+(r.models?r.models.length+' моделей':'ошибка')}catch(e){document.getElementById('llmStatus').textContent='❌ Ошибка: '+e.message;console.error('testLlm',e)}}
async function loadCharacterPresets(){try{const r=await api('character_presets');const sel=document.getElementById('presetList');sel.innerHTML='';for(const p of r.presets||[]){const opt=document.createElement('option');opt.value=p.path;opt.textContent=p.name;if(p.path===r.current)opt.selected=true;sel.appendChild(opt)}const en=document.getElementById('presetEnabled');en.checked=r.preset_enabled!==false;document.getElementById('presetEnabledLabel').textContent='Пресет: '+(r.preset_enabled!==false?'Включено':'Выключено');if(r.custom_path)document.getElementById('customModelPath').value=r.custom_path;const ss=document.getElementById('charScreenshotEnabled');const mcp=ss&&r.screenshot_mcp_enabled;if(ss){ss.checked=mcp!==false;document.getElementById('charScreenshotLabel').textContent='Скриншот: '+(mcp!==false?'Включено':'Выключено')}}catch(e){console.error('loadCharacterPresets',e)}}
async function togglePreset(enabled){document.getElementById('presetEnabledLabel').textContent='Пресет: '+(enabled?'Включено':'Выключено')}
async function toggleCharScreenshot(enabled){document.getElementById('charScreenshotLabel').textContent='Скриншот: '+(enabled?'Включено':'Выключено');const r=await api('toggle_screenshot_mcp',{enabled:enabled});if(r&&r.status==='ok'&&r.enabled!==undefined&&r.enabled!==null)document.getElementById('charScreenshotEnabled').checked=r.enabled}
async function selectPreset(path){if(path)document.getElementById('customModelPath').value=''}
async function saveCharacterPreset(){try{const enabled=document.getElementById('presetEnabled').checked;const preset=document.getElementById('presetList').value;const custom=document.getElementById('customModelPath').value.trim();const ss=document.getElementById('charScreenshotEnabled')?document.getElementById('charScreenshotEnabled').checked:true;const r=await api('character_preset',{enabled,preset,custom_path:custom,screenshot_mcp_enabled:ss});document.getElementById('characterStatus').textContent='✅ Сохранено';setTimeout(()=>document.getElementById('characterStatus').textContent='● Готов',2000)}catch(e){document.getElementById('characterStatus').textContent='❌ '+e.message;console.error('saveCharacterPreset',e)}}

async function loadSystemInfo(){try{const r=await api('system_info');const info=document.getElementById('systemInfo');info.innerHTML=(r.os?'<b>ОС:</b> '+r.os+'<br>':'')+(r.cpu?'<b>CPU:</b> '+r.cpu+'<br>':'')+(r.ram?'<b>RAM:</b> '+r.ram+'<br>':'')+(r.python?'<b>Python:</b> '+r.python+'<br>':'')+(r.hostname?'<b>Хост:</b> '+r.hostname+'<br>':'')+(r.uptime?'<b>Аптайм:</b> '+r.uptime+'<br>':'')+(r.mcp?'<b>MCP сервер:</b> '+(r.mcp.running?'✅ Запущен на '+r.mcp.port:'❌ Остановлен')+'<br>':'')+(r.mcp&&r.mcp.num_tools?'<b>MCP инструментов:</b> '+r.mcp.num_tools:'')}catch(e){document.getElementById('systemInfo').textContent='❌ Ошибка: '+e.message;console.error('loadSystemInfo',e)}}
async function toggleMcpServer(enabled){try{await api('mcp_toggle',{enabled});document.getElementById('mcpServerLabel').textContent='MCP сервер: '+(enabled?'Включено':'Выключено');document.getElementById('mcpStatus').textContent='✅ Сохранено';setTimeout(()=>document.getElementById('mcpStatus').textContent='● Готов',2000)}catch(e){console.error('toggleMcpServer',e)}}

async function mcpTtsLoadEngines(){try{const re=await api('tts_engines');const sel=document.getElementById('mcpTtsEngine');if(!sel)return;sel.innerHTML='';let cur=re.current_engine||'piper';for(const e of re.engines){const opt=document.createElement('option');opt.value=e;opt.textContent=e==='xtts'?'XTTS v2':'Piper';if(e===cur)opt.selected=true;sel.appendChild(opt)}const rs=await api('settings');const vol=document.getElementById('mcpTtsVolume');if(vol){vol.value=Math.round(rs.volume*100);const vl=document.getElementById('mcpTtsVolLabel');if(vl)vl.textContent=Math.round(rs.volume*100)+'%'}const en=document.getElementById('mcpTtsEnabled');if(en){en.checked=rs.enabled;const el=document.getElementById('mcpTtsEnabledLabel');if(el)el.textContent='TTS: '+(rs.enabled?'Включено':'Выключено')}await mcpTtsLoadVoices(cur)}catch(e){console.error('mcpTtsLoadEngines',e)}}
async function mcpTtsEngineChange(){try{const e=document.getElementById('mcpTtsEngine');if(e)await mcpTtsLoadVoices(e.value)}catch(e){console.error('mcpTtsEngineChange',e)}}
async function mcpTtsLoadVoices(engine){try{const r=await api('voices');const sel=document.getElementById('mcpTtsVoice');if(!sel)return;sel.innerHTML='';const e=engine||'piper';for(const v of r.voices){if(e==='piper'&&v.startsWith('xtts:'))continue;if(e==='xtts'&&!v.startsWith('xtts:'))continue;const opt=document.createElement('option');opt.value=v;opt.textContent=v.replace('xtts:','');sel.appendChild(opt)}}catch(e){console.error('mcpTtsLoadVoices',e)}}
async function mcpTtsSetVolume(v){const vl=document.getElementById('mcpTtsVolLabel');if(vl)vl.textContent=v+'%';await api('settings',{volume:v/100})}
async function mcpTtsToggle(){const en=document.getElementById('mcpTtsEnabled');if(!en)return;const checked=en.checked;const el=document.getElementById('mcpTtsEnabledLabel');if(el)el.textContent='TTS: '+(checked?'Включено':'Выключено');await api('settings',{enabled:checked})}
let _mcpVersion = 0;

async function loadMcpConfig(){try{const v=_mcpVersion;const r=await api('mcp_config');if(v!==_mcpVersion)return;log('loadMcp: v='+v+' ss='+r.screenshot_mcp_enabled+' global='+r.global_enabled);const g=document.getElementById('mcpGlobalEnabled');if(g){g.checked=r.global_enabled!==false;document.getElementById('mcpGlobalLabel').textContent='Глобальный MCP: '+(r.global_enabled!==false?'Включено':'Выключено')}const map={music:r.music_mcp_enabled,alarm:r.alarm_mcp_enabled,timer:r.timer_mcp_enabled,screenshot:r.screenshot_mcp_enabled,hide:r.hide_mcp_enabled,control:r.control_mcp_enabled,emotion:r.emotion_mcp_enabled};const names={music:'Управление музыкой',alarm:'Управление будильником',timer:'Управление таймером',screenshot:'Скриншоты',hide:'Скрытие персонажа',control:'Управление персонажем',emotion:'Эмоции персонажа'};for(const[k,v]of Object.entries(map)){const el=document.getElementById('mcp'+k.charAt(0).toUpperCase()+k.slice(1)+'Perm');if(el){el.checked=v!==false;const lbl=document.getElementById('mcp'+k.charAt(0).toUpperCase()+k.slice(1)+'PermLabel');if(lbl)lbl.textContent=(names[k]||k)+(v!==false?'':' (запрещено)')}}const ss=document.getElementById('mcpServerEnabled');if(ss){ss.checked=r.mcp_server_running;document.getElementById('mcpServerLabel').textContent='MCP сервер: '+(r.mcp_server_running?'Включено':'Выключено')}document.getElementById('mcpStatus').textContent='● Готов';mcpTtsLoadEngines()}catch(e){document.getElementById('mcpStatus').textContent='❌ Ошибка: '+e.message;console.error('loadMcpConfig',e)}}
async function saveMcpConfig(){try{const v=++_mcpVersion;const global=document.getElementById('mcpGlobalEnabled').checked;const data={global_enabled:global,music_mcp_enabled:document.getElementById('mcpMusicPerm').checked,alarm_mcp_enabled:document.getElementById('mcpAlarmPerm').checked,timer_mcp_enabled:document.getElementById('mcpTimerPerm').checked,screenshot_mcp_enabled:document.getElementById('mcpScreenshotPerm').checked,hide_mcp_enabled:document.getElementById('mcpHidePerm').checked,control_mcp_enabled:document.getElementById('mcpControlPerm').checked,emotion_mcp_enabled:document.getElementById('mcpEmotionPerm').checked};log('saveMcp: v='+v+' global='+global+' ss='+data.screenshot_mcp_enabled);await api('save_mcp_config',data);if(v!==_mcpVersion){log('saveMcp: SKIP v='+v+' cur='+_mcpVersion);return}document.getElementById('mcpStatus').textContent='✅ Сохранено';await loadMcpConfig();document.getElementById('mcpStatus').textContent='✅ Сохранено';setTimeout(()=>document.getElementById('mcpStatus').textContent='● Готов',2000)}catch(e){console.error('saveMcpConfig',e)}}
